(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cargo-process--command-clippy "+nightly clippy -Zunstable-options")
 '(company-box-scrollbar ''left)
 '(company-frontends
   '(company-pseudo-tooltip-unless-just-one-frontend company-echo-metadata-frontend company-preview-if-just-one-frontend))
 '(company-idle-delay 0.5)
 '(company-lsp-cache-candidates nil)
 '(company-lsp-filter-candidates
   '((bingo)
     (ccls)
     (clangd)
     (cquery)
     (go-bingo)
     (gopls)
     (javacomp)
     (jdtls)
     (pyls)
     (rust-analyzer)
     (rls)
     (t)))
 '(company-minimum-prefix-length 1)
 '(company-posframe-mode t)
 '(company-quickhelp-mode t)
 '(company-tooltip-align-annotations t)
 '(company-tooltip-flip-when-above t)
 '(company-transformers '(dia/company-transform))
 '(ede-project-directories '("/usr/src/zen/zen-kernel"))
 '(editorconfig-mode t)
 '(eldoc-echo-area-use-multiline-p 'truncate-sym-name-if-fit)
 '(gas-opcode-column 9)
 '(global-company-mode t)
 '(helm-completion-style 'emacs)
 '(lsp-auto-execute-action nil)
 '(lsp-auto-guess-root t)
 '(lsp-completion-no-cache t)
 '(lsp-completion-provider :none)
 '(lsp-headerline-breadcrumb-enable t)
 '(lsp-headerline-breadcrumb-segments '(project path-up-to-project file symbols))
 '(lsp-lens-enable t)
 '(lsp-rust-analyzer-cargo-run-build-scripts t)
 '(lsp-rust-analyzer-display-chaining-hints t t)
 '(lsp-rust-analyzer-display-closure-return-type-hints t)
 '(lsp-rust-analyzer-display-lifetime-elision-hints-enable "always")
 '(lsp-rust-analyzer-display-lifetime-elision-hints-use-parameter-names t)
 '(lsp-rust-analyzer-display-parameter-hints t t)
 '(lsp-rust-analyzer-display-reborrow-hints t)
 '(lsp-rust-analyzer-experimental-proc-attr-macros t t)
 '(lsp-rust-analyzer-inlay-face 'lsp-face-semhl-label)
 '(lsp-rust-analyzer-macro-expansion-method 'dia/rust-analyzer-macro-expand t)
 '(lsp-rust-analyzer-proc-macro-enable t t)
 '(lsp-rust-analyzer-rustfmt-extra-args [])
 '(lsp-rust-analyzer-rustfmt-override-command ["rustup run stable rustfmt"])
 '(lsp-rust-analyzer-server-display-inlay-hints t t)
 '(lsp-rust-unstable-features t)
 '(lsp-semantic-tokens-enable t)
 '(lsp-semantic-tokens-warn-on-missing-face nil)
 '(lsp-server-trace "verbose")
 '(lsp-typescript-implementations-code-lens-enabled t)
 '(lsp-typescript-references-code-lens-enabled t)
 '(lsp-ui-doc-alignment 'window)
 '(lsp-ui-doc-enable t)
 '(lsp-ui-doc-include-signature t)
 '(lsp-ui-doc-max-height 15)
 '(lsp-ui-doc-max-width 80)
 '(lsp-ui-doc-show-with-cursor nil)
 '(lsp-ui-flycheck-list-position 'bottom)
 '(lsp-ui-sideline-actions-icon "~/.emacs.d/icons/idea2-256x256.png")
 '(lsp-ui-sideline-diagnostic-max-line-length 60)
 '(lsp-ui-sideline-diagnostic-max-lines 3)
 '(lsp-ui-sideline-ignore-duplicate t)
 '(lsp-ui-sideline-show-hover nil)
 '(lsp-ui-sideline-show-symbol t)
 '(mips-indent-character 11)
 '(mips-operands-column 25)
 '(mips-operator-column 17)
 '(org-agenda-files
   '("~/Documents/org/notes.org" "~/Documents/org/work.org" "~/Documents/org/home.org" "~/Documents/org/links.org" "~/Documents/org/daily.org"))
 '(org-default-notes-file "~/Documents/org/notes.org")
 '(org-directory "~/Documents/org")
 '(org-indent-mode t)
 '(org-log-done t)
 '(org-return-follows-link t)
 '(org-startup-folded nil)
 '(package-selected-packages
   '(helm-lsp doom-themes company-tabnine unicode-fonts fontawesome auto-yasnippet helm-company lsp-treemacs treemacs rustic-mode company-lsp zygospore yasnippet-snippets yaml-mode ws-butler which-key web-mode web-beautify vue-mode volatile-highlights use-package-ensure-system-package undo-tree treemacs-projectile toml-mode swiper-helm sublime-themes sr-speedbar sqlup-mode sql-indent slime rustic realgud popup-switcher php-eldoc paredit multi-compile magit lsp-ui iedit highlight-parentheses helpful helm-swoop helm-rg helm-projectile helm-posframe helm-gtags helm-ag go-rename go-eldoc go-dlv go-autocomplete git-gutter-fringe git-gutter-fringe+ git-blamed ggtags function-args fn flycheck expand-region erlang editorconfig dtrt-indent doom-modeline diminish dap-mode counsel-projectile company-quickhelp company-posframe company-php company-go company-c-headers company-box comment-dwim-2 clean-aindent-mode clang-format bug-hunter bash-completion auto-package-update anzu aggressive-indent adoc-mode))
 '(rustic-ansi-faces
   ["black" "red3" "green3" "yellow3" "deepskyblue" "magenta3" "cyan3" "white"])
 '(rustic-babel-display-compilation-buffer t)
 '(rustic-lsp-server 'rust-analyzer)
 '(safe-local-variable-values
   '(eval
     (when
	 (require 'rainbow-mode nil t)
       (rainbow-mode 1))))
 '(tramp-syntax 'default nil (tramp))
 '(warning-suppress-types '((use-package))))

;;  '(default ((t (:background nil))))
;;  ;; '(default ((t (:family "Anonymous Pro Regular" :foundry "outline" :slant normal :weight bold :height 113 :width normal))))
;;  '(cperl-array-face ((t (:inherit font-lock-variable-name-face :slant italic :weight bold))))
;;  '(cperl-hash-face ((t (:inherit font-lock-variable-name-face :slant italic :weight bold))))
;;  '(fa-face-hint ((t (:inherit font-lock-variable-name-face :slant italic :weight bold))))
;;  '(fa-face-hint-bold ((t (:inherit font-lock-variable-name-face :slant italic :weight bold)))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:background nil))))
 '(cperl-array-face ((t (:inherit font-lock-variable-name-face :slant italic :weight bold))))
 '(cperl-hash-face ((t (:inherit font-lock-variable-name-face :slant italic :weight bold))))
 '(fa-face-hint ((t (:inherit font-lock-variable-name-face :slant italic :weight bold))))
 '(fa-face-hint-bold ((t (:inherit font-lock-variable-name-face :slant italic :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "DarkGoldenrod3" :weight bold :family "Anonymous Pro"))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F" :slant italic :height 0.98))))
 '(font-lock-type-face ((t (:foreground "seashell4"))))
 '(lsp-face-semhl-comment ((t (:foreground "#7F9F7F" :slant normal :height 1.0))))
 '(lsp-face-semhl-default-library ((t (:inherit font-lock-builtin-face))))
 '(lsp-face-semhl-function ((t (:inherit font-lock-function-name-face :slant normal))))
 '(lsp-face-semhl-interface ((t (:inherit nil :foreground "cadet blue"))))
 '(lsp-face-semhl-label ((t (:inherit font-lock-comment-face :slant italic :height 1.0))))
 '(lsp-face-semhl-macro ((t (:inherit font-lock-preprocessor-face))))
 '(lsp-face-semhl-method ((t (:inherit lsp-face-semhl-function :slant italic))))
 '(lsp-face-semhl-namespace ((t (:inherit nil :foreground "rosy brown" :weight bold))))
 '(lsp-ui-doc-background ((t (:background "#272A36" :family "Anonymous Pro"))))
 '(lsp-ui-doc-header ((t (:background "deep sky blue" :foreground "black" :family "Anonymous Pro"))))
 '(lsp-ui-doc-url ((t (:inherit link :family "Anonymous Pro"))))
 '(lsp-ui-sideline-code-action ((t (:foreground "yellow" :family "Anonymous Pro"))))
 '(lsp-ui-sideline-current-symbol ((t (:foreground "white" :box (:line-width (1 . -1) :color "white") :weight ultra-bold :height 0.99))))
 '(lsp-ui-sideline-global ((t (:foreground "deep sky blue" :family "Anonymous Pro"))))
 '(mode-line ((t (:weight light :height 110 :family "Firacode"))))
 '(mode-line-inactive ((t (:weight light :height 110 :family "Firacode"))))
 '(rustic-compilation-column ((t (:inherit default :foreground "deep sky blue"))))
 '(rustic-compilation-error ((t (:inherit default :foreground "dark violet"))))
 '(rustic-compilation-info ((t (:inherit default :foreground "burlywood"))))
 '(rustic-compilation-line ((t (:inherit default :foreground "deep sky blue"))))
 '(rustic-compilation-warning ((t (:inherit default :foreground "dark salmon"))))
 '(rustic-message ((t (:inherit default :foreground "burlywood")))))
